package blacksmith;

public enum ItemTier {
	NONE, WOODEN, STONE, COPPER, TIN, BRASS, BRONZE, IRON, STEEL, SILVER, GOLD, DIAMOND, MITHRIL, ADAMANTITE, COBALT, HELLSTONE, LEGENDARIUM, MUSTACHIUM, XENOTINE, UNOBTAINIUM;
}
